# -*- coding: utf-8 -*-
"""config.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1CAHkh8CTEVNJ_HPGupuxWFUTNlgLOg0A
"""

TOP_UNIVERSE_SIZE = 500

LARGE_CAP = 100
MID_CAP = 250

EMA_PERIOD = 100
VOL_PERIOD = 20

MIN_DAILY_MOVE = 0.05

HARD_SL = 0.10
TRAIL_SL = 0.20
TRAIL_START = 20

MAX_HOLD_DAYS = 126

RETURN_WINDOWS = {
    "5D":5,
    "20D":20,
    "3M":63,
    "6M":126
}

GOOGLE_SHEET_NAME = "DailySignals"