# -*- coding: utf-8 -*-
"""returns_tracker.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/12EBjoJAim8WQgZ2fuTuQvwznfMRCrBxX
"""

from config import RETURN_WINDOWS


def compute_forward_returns(df,entry_index):

    entry_price = df.iloc[entry_index]["Close"]

    returns={}

    for name,days in RETURN_WINDOWS.items():

        if entry_index+days < len(df):

            future_price = df.iloc[entry_index+days]["Close"]

            returns[name]=(future_price-entry_price)/entry_price

        else:

            returns[name]=None

    return returns