# -*- coding: utf-8 -*-
"""trade_manager.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1bhEjJnokCFlmSXVVp1mr4SU74cTIUcQq
"""

import pandas as pd
from config import HARD_SL, TRAIL_SL, MAX_HOLD_DAYS


def update_trades(price_df):

    trades = pd.read_csv("storage/active_trades.csv")

    closed=[]

    for i,row in trades.iterrows():

        symbol=row["symbol"]

        entry=row["entry_price"]

        stock=price_df[price_df["symbol"]==symbol]

        if len(stock)==0:
            continue

        last=stock.iloc[-1]

        price=last["Close"]

        if price <= entry*(1-HARD_SL):

            row["exit_reason"]="Hard SL"

            row["exit_price"]=price

        elif price <= stock["High"].max()*(1-TRAIL_SL):

            row["exit_reason"]="Trailing SL"

            row["exit_price"]=price

        else:

            continue


        row["final_return"]=(row["exit_price"]-entry)/entry

        closed.append(row)

    return pd.DataFrame(closed)