# -*- coding: utf-8 -*-
"""universe_builder.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1e37RJ-XYIMK8_kh8tFPqy-OUeErzSXL-
"""

import pandas as pd
import yfinance as yf
from config import TOP_UNIVERSE_SIZE, LARGE_CAP, MID_CAP

NIFTY500_TICKERS_URL = "https://archives.nseindia.com/content/indices/ind_nifty500list.csv"


def fetch_universe():

    df = pd.read_csv(NIFTY500_TICKERS_URL)

    df["symbol"] = df["Symbol"] + ".NS"

    symbols = df["symbol"].tolist()

    return symbols


def fetch_market_caps(symbols):

    caps = []

    for s in symbols:

        try:
            info = yf.Ticker(s).info
            mcap = info.get("marketCap",0)

            caps.append((s,mcap))

        except:
            continue

    df = pd.DataFrame(caps,columns=["symbol","mcap"])

    df = df.sort_values("mcap",ascending=False)

    df = df.head(TOP_UNIVERSE_SIZE)

    df["rank"] = range(1,len(df)+1)

    df["bucket"] = df["rank"].apply(bucket_classifier)

    df.to_csv("storage/universe.csv",index=False)

    return df


def bucket_classifier(rank):

    if rank <= LARGE_CAP:
        return "Large"

    if rank <= MID_CAP:
        return "Mid"

    return "Small"