# -*- coding: utf-8 -*-
"""sheet_manager.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1cmrsv8SiFbZfVlg3Nq_TJnLdqSnB2Z7B
"""
import httplib2
import certifi
import os

os.environ["SSL_CERT_FILE"] = certifi.where()
os.environ["REQUESTS_CA_BUNDLE"] = certifi.where()

# Then your existing gspread auth code below...
import gspread
from oauth2client.service_account import ServiceAccountCredentials
from config import GOOGLE_SHEET_NAME


scope=[
"https://spreadsheets.google.com/feeds",
"https://www.googleapis.com/auth/drive"
]

creds = ServiceAccountCredentials.from_json_keyfile_name(
"credentials.json",
scope
)

client = gspread.authorize(creds)


def update_sheet(df):

    sheet = client.open(GOOGLE_SHEET_NAME).sheet1

    sheet.clear()

    sheet.update(
        [df.columns.values.tolist()] + df.values.tolist()
    )